<div id="content">

	<div id="code-editor">
		<form class="url-form" method="post" action="/index" name="openUrl">
			<label for="url">URL:</label>
			<input type="text" name="url" />
			<input type="submit" value="Ir"/>
		</form>
		<ul id="lang-menu">
	        <li l="html"><a href="#tabs-1">HTML</a></li>
	        <li l="css"><a href="#tabs-2">CSS</a></li>
	        <li l="javascript"><a href="#tabs-3">JavaScript</a></li>
	    </ul>
	    <div id="tabs-1">
	    	<?php if($this->contents): ?>
	    		<textarea id="html-editor"><?php echo $this->contents; ?></textarea>
	    	<?php else: ?>
	    		<textarea id="html-editor">
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="http://projetofinal.dev/temp/529d9a1cc503a3db534884f5d6a2a2f3/user/default.css" />
  </head>
  <body>

  </body>
  <script type="text/javaScript" src="http://projetofinal.dev/temp/529d9a1cc503a3db534884f5d6a2a2f3/user/default.js"></script>
</html></textarea>
	 		<?php endif; ?>
	        
	    </div>
	    <div id="tabs-2">
	    	<div class="sub-tabs">
	    		<?php if($this->post == 1): ?>
	    			<?php if($this->css): ?>
		    			<?php foreach($this->css as $name => $css): ?>
			    			<span class="sub-tab" file="<?php echo $css[0]; ?>"><?php echo $name; ?></span>
			    		<?php endforeach; ?>
		    		<?php endif; ?>
	    		<?php else: ?>
		    		<span class="sub-tab" file="<?php echo $this->defaultCSS; ?>">default.css</span>
		    	<?php endif; ?>
		   </div>
	        <textarea id="css-editor" class="css-editor"></textarea>
	    </div>
	    <div id="tabs-3">
	    	<div class="sub-tabs">
	    		<?php if($this->post == 1): ?>
	    			<?php if($this->javascripts): ?>
		    			<?php foreach($this->javascripts as $name => $js): ?>
			    			<span class="sub-tab" file="<?php echo $js[0]; ?>"><?php echo $name; ?></span>
			    		<?php endforeach; ?>
		    		<?php endif; ?>
	    		<?php else: ?>
		    		<span class="sub-tab" file="<?php echo $this->defaultJS; ?>">default.js</span>
		    	<?php endif; ?>
		   </div>
	        <textarea id="javascript-editor" class="javascript-editor"></textarea>
	    </div>	
	</div>
	
	<div id="smartphone">
		<div id="simulation"><?php echo $this->contents; ?></div>
		<span id="resize">Resize</span>
	</div>
	<div class="clear"></div>
</div>
