<div id="content">

	<div id="code-editor">
		<ul id="lang-menu">
	        <li><a href="#tabs-1">HTML</a></li>
	        <li><a href="#tabs-2">CSS</a></li>
	        <li><a href="#tabs-3">JavaScript</a></li>
	    </ul>
	    <div id="tabs-1">
	        <textarea id="html-editor"><?php echo $this->contents; ?></textarea>
	    </div>
	    <div id="tabs-2">
	        <textarea id="css-editor"><?php echo $this->firstCss; ?></textarea>
	    </div>
	    <div id="tabs-3">
	        <textarea id="javascript-editor"><?php echo $this->firstJavascript; ?></textarea>
	    </div>	
	</div>
	
	<div id="smartphone">
		<form method="post" action="/index" name="openUrl">
			<input type="text" name="url" />
			<input type="submit" />
		</form>
		<div id="simulation"><?php echo $this->contents; ?></div>
	</div>
	<div class="clear"></div>
	<div class="links">
		<b>JavaScript</b><br />
		<?php if(isset($this->javascripts))
				foreach($this->javascripts as $file) 
					echo $file . '<br />';
		?>
		<br />
		<b>CSS</b><br />
		<?php if(isset($this->css))
				foreach($this->css as $file) 
					echo $file . '<br />';
		?>
	</div>

</div>


