<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8" />
		<meta name="author" content="Flora Saramago" />
		
		<title>Projeto Final</title>
		
		
		<!-- <link rel="stylesheet" media="screen" type="text/css" href="<?php echo PATH_PUBLIC; ?>/css/vendors/jquery-ui-1.9.1.custom.min.css" />
		<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/jquery-1.8.2.min.js"></script>
		<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/jquery-ui-1.9.1.custom.min.js"></script> -->


		<!--<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css" />-->
    
    	<link rel="stylesheet" media="screen" type="text/css" href="<?php echo PATH_PUBLIC; ?>/css/vendors/jquery-ui-1.10.0.custom.min.css" /> 
	    <link rel="stylesheet" media="screen" type="text/css" href="<?php echo PATH_PUBLIC; ?>/css/vendors/codemirror.css" />
		<link rel="stylesheet" media="screen" type="text/css" href="<?php echo PATH_PUBLIC; ?>/css/vendors/solarized.css" />    
		<link rel="stylesheet" media="screen" type="text/css" href="<?php echo PATH_PUBLIC; ?>/css/style_site.css" />

	</head>

	<body>
		
		<?php echo $this->layout()->content; ?>
				
	</body>
	<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/jquery.min.js"></script>
	<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/jquery-ui-1.10.0.custom.min.js"></script>
	<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/codemirror.js"></script>
	<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/xml.js"></script>
	<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/javascript.js"></script>
	<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/css.js"></script>
	<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/htmlmixed.js"></script>
	<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/script_site.js"></script>
</html>
