<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8" />
		<meta name="author" content="Flora Saramago" />
		
		<title>Projeto Final</title>
		
		
		<link rel="stylesheet" media="screen" type="text/css" href="<?php echo PATH_PUBLIC; ?>/css/vendors/jquery-ui-1.9.1.custom.min.css" />
		
		<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/jquery-1.8.2.min.js"></script>
		<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/jquery-ui-1.9.1.custom.min.js"></script>
		<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/script_site.js"></script>

		<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css" />
    <!--<script src="http://code.jquery.com/jquery-1.8.2.js"></script>
     <script src="http://code.jquery.com/ui/1.9.1/jquery-ui.js"></script> -->
    
<link rel="stylesheet" media="screen" type="text/css" href="<?php echo PATH_PUBLIC; ?>/css/vendors/codemirror.css" />

<link rel="stylesheet" media="screen" type="text/css" href="<?php echo PATH_PUBLIC; ?>/css/vendors/solarized.css" />    
<link rel="stylesheet" media="screen" type="text/css" href="<?php echo PATH_PUBLIC; ?>/css/style_site.css" />

<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/codemirror.js"></script>
<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/xml.js"></script>
<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/javascript.js"></script>
<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/css.js"></script>
<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/htmlmixed.js"></script>
	</head>

	<body>
		
		<?php echo $this->layout()->content; ?>
				
	</body>
</html>
