<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8" />
		<meta name="author" content="Flora Saramago" />
		
		<title>Projeto Final</title>
		
		<link rel="stylesheet" media="screen" type="text/css" href="<?php echo PATH_PUBLIC; ?>/css/style_site.css" />
		
		<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/vendors/jquery-1.7.1.min.js"></script>
		<script type="text/javaScript" src="<?php echo PATH_PUBLIC; ?>/js/script_site.js"></script>
	</head>

	<body>
		
		<?php echo $this->layout()->content; ?>
				
	</body>
</html>
