<div style="padding: 10px 15px;">
<h1>Erro 403</h1>

<!--  CSRF Prevention -->
<p>Ooops, erro ao tentar acessar esta página.</p>

<?php

echo $this->message;

if (APPLICATION_ENV == 'development') {
	echo '<hr /><h2 style="font-size: 14px;margin-bottom: 10px;">Development use:</h2>';
	if (isset($this->exception)) {
		echo '<h3>' . get_class($this->exception)    . '</h3>'
		. '<p>'     . $this->exception->getMessage() . '</p><pre>';
		print_r($this->exception->getTrace());
		echo '</pre>';
	}
}
?></div>
