<html>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		<meta http-equiv="Content-language" content="pt-br" />
		<link rel="stylesheet" type="text/css" href="/css/style_errors.css" />
		<script type="text/javascript" src="/js/vendors/backlink.js"></script>
	</head>
	<body>
		<div id="wrap">
			<div class="msg">
				<h1>404</h1>
				<p>Página não encontrada.</p>
				<span id="back-link">
					<SCRIPT TYPE="text/javascript">
						<!--
						var gb = new backlink();
						gb.text = "Voltar";
						gb.id = "back-link";
						gb.write();
						//-->
					</SCRIPT>
				</span>
				
			</div>
		</div>
		
		<?php
			if (APPLICATION_ENV == 'development') {
				echo '<hr /><h2 style="font-size: 14px;margin-bottom: 10px;">Development use:</h2>';
				echo '<h3>' . get_class($this->exception)    . '</h3>'
				. '<p>'     . $this->exception->getMessage() . '</p><pre>';
				print_r($this->exception->getTrace());
				echo '</pre>';
			}
			?>
	
	</body>
</html>